language: generic
os: linux
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  jobs:
    - EMACS_VERSION=25.1
    - EMACS_VERSION=25.2
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
    - EMACS_VERSION=26.2
    - EMACS_VERSION=26.3
    - EMACS_VERSION=master
jobs:
  allow_failures:
    - env: EMACS_VERSION=master
install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version
script:
  ./ci/run.sh
